# framework:
#     cache:
#         default_redis_provider: 'redis://localhost' # Or use an environment variable like '%env(resolve:REDIS_URL)%'
#         pools:
#             doctrine.result_cache_pool:
#                 adapter: cache.adapter.redis
#                 provider: default_redis_provider
#             doctrine.query_cache_pool:
#                 adapter: cache.adapter.redis
#                 provider: default_redis_provider

framework:
  cache:
    default_redis_provider: '%env(REDIS_URL)%'  # e.g. REDIS_URL=redis://127.0.0.1:6379
    pools:
      doctrine.result_cache_pool:
        adapter: cache.adapter.redis
      doctrine.query_cache_pool:
        adapter: cache.adapter.redis
        
# framework:
#     cache:
#         pools:
#             doctrine.result_cache_pool:
#                 adapter: cache.adapter.redis
#                 provider: default_redis_provider
#             doctrine.query_cache_pool:
#                 adapter: cache.adapter.redis
#                 provider: default_redis_provider

# framework:
#     cache:
#         pools:
#             cache.my_redis_pool:
#                 adapter: cache.adapter.redis
#                 provider: 'redis://localhost:6379'