repos:
  - repo: local
    hooks:

      - id: phpstan
        name: PHPStan
        entry: vendor/bin/phpstan analyse
        language: system
        types: [php]
        args: [--memory-limit=-1]

      - id: phpcs
        name: PHP CodeSniffer
        entry: vendor/bin/phpcs
        language: system
        files: \.php$
        args: ["--standard=PSR12"]
        types: [php]